# docker-compose.full.yml
networks:
  mlops_net:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  uptime_kuma_data:
  grafana_data:
  prometheus_data:
  rabbitmq_data:
  redis_data:

services:
  # ==========================================
  # 1. CORE INFRASTRUCTURE (MLflow & Storage)
  # ==========================================
  db:
    image: postgres:15-alpine
    container_name: mlfactory_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mlflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mlflow}
      POSTGRES_DB: ${POSTGRES_DB:-mlflowdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlops_net

  minio:
    image: minio/minio:latest
    container_name: mlfactory_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password123}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - mlops_net

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlfactory_mlflow
    restart: always
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER:-mlflow}:${POSTGRES_PASSWORD:-mlflow}@db:5432/${POSTGRES_DB:-mlflowdb}
      --default-artifact-root s3://${AWS_BUCKET_NAME:-mlflow-models}
      --host 0.0.0.0
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-admin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-password123}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_IGNORE_TLS: "true"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    networks:
      - mlops_net

  # ==========================================
  # 2. MESSAGE BROKER & BACKEND (Asynchrone)
  # ==========================================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mlfactory_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"   # Port de communication Celery
      - "15672:15672" # Interface Web RabbitMQ
      - "15692:15692" # Port d'export des métriques pour Prometheus !
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mlops_net

  redis:
    image: redis:7-alpine
    container_name: mlfactory_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mlops_net

  # ==========================================
  # 3. APPLICATION METIER (API, Front, Worker)
  # ==========================================
  api:
    build: 
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: mlfactory_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-admin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-password123}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - rabbitmq
      - redis
      - mlflow
    networks:
      - mlops_net
    deploy:
      resources:
        limits:
          memory: 512M

  worker:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: mlfactory_worker_celery
    restart: always
    command: uv run celery -A src.worker.tasks worker --loglevel=info
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-admin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-password123}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - rabbitmq
      - redis
      - mlflow
    networks:
      - mlops_net

  front:
    build:
      context: .
      dockerfile: ./src/front/Dockerfile
    container_name: mlfactory_front
    restart: always
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - mlops_net